import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google"
import "./globals.css";
import LenisScroll from "./_component/LenisScroll";


const playfair = Playfair_Display({ 
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} antialiased`}
      >
        <LenisScroll />
        {children}
      </body>
    </html>
  );
}
